Vagrant.configure("2") do |config|
  config.vm.name = "kafka2"
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "public_network", bridge: "wlp4s0", ip: "192.168.251.252"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
    timedatectl set-timezone Asia/Jakarta
    apt-get update
    hostnamectl set-hostname kafka2
  SHELL
end
